opa version verfification

diff --git a/.github/workflows/opa_s3_bucket_tag_policy_check.yml b/.github/workflows/opa_s3_bucket_tag_policy_check.yml
--- a/.github/workflows/opa_s3_bucket_tag_policy_check.yml
+++ b/.github/workflows/opa_s3_bucket_tag_policy_check.yml
@@ -53,5 +53,9 @@ jobs:
         run: |
           for policy in ./policies/*.rego; do
             echo "Testing policy: $policy"
-            opa eval --format pretty --fail-defined --data "$policy" --input opa_input.json "data.policies.s3_bucket_tag_violation"
+            opa eval --format pretty --fail-defined --data "$policy" --input opa_input.json "data.policies.s3_bucket_tag_violation_msgs"
+            if [ $? -ne 0 ]; then
+              echo "Policy $policy failed. Exiting."
+              exit 1
+            fi  
           done
